#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <d3d9.h>
#include <cstdio>
#include <cstdarg>
#include <intrin.h>
// Diagnostic forwarding proxy, not a replacement for Windows Direct3D.
// Loaded only beside the public reference client on an isolated test runner.
static SRWLOCK guard=SRWLOCK_INIT;
static void log(const char* fmt,...){AcquireSRWLockExclusive(&guard);FILE* f=nullptr;fopen_s(&f,"native-d3d9-trace.txt","a");if(f){va_list a;va_start(a,fmt);vfprintf(f,fmt,a);va_end(a);fputc('\n',f);fclose(f);}ReleaseSRWLockExclusive(&guard);}
static void** original=nullptr;static void** deviceOriginal=nullptr;
using Make=IDirect3D9*(WINAPI*)(UINT);
static Make systemMake(){static Make fn=nullptr;if(!fn){wchar_t path[MAX_PATH]={};GetSystemDirectoryW(path,MAX_PATH);wcscat_s(path,L"\\d3d9.dll");HMODULE m=LoadLibraryW(path);fn=m?reinterpret_cast<Make>(GetProcAddress(m,"Direct3DCreate9")):nullptr;}return fn;}
static HRESULT STDMETHODCALLTYPE caps(IDirect3D9* p,UINT a,D3DDEVTYPE t,D3DCAPS9* c){using F=HRESULT(STDMETHODCALLTYPE*)(IDirect3D9*,UINT,D3DDEVTYPE,D3DCAPS9*);auto hr=reinterpret_cast<F>(original[14])(p,a,t,c);log("GetDeviceCaps a=%u t=%u hr=%08x caps=%08x vs=%08x ps=%08x caller=%p",a,t,hr,SUCCEEDED(hr)?c->DevCaps:0,SUCCEEDED(hr)?c->VertexShaderVersion:0,SUCCEEDED(hr)?c->PixelShaderVersion:0,_ReturnAddress());return hr;}
static HRESULT STDMETHODCALLTYPE type(IDirect3D9* p,UINT a,D3DDEVTYPE t,D3DFORMAT x,D3DFORMAT y,BOOL w){using F=HRESULT(STDMETHODCALLTYPE*)(IDirect3D9*,UINT,D3DDEVTYPE,D3DFORMAT,D3DFORMAT,BOOL);auto hr=reinterpret_cast<F>(original[9])(p,a,t,x,y,w);log("CheckDeviceType a=%u type=%u formats=%u/%u window=%u hr=%08x caller=%p",a,t,x,y,w,hr,_ReturnAddress());return hr;}
static HRESULT STDMETHODCALLTYPE format(IDirect3D9* p,UINT a,D3DDEVTYPE t,D3DFORMAT f,DWORD u,D3DRESOURCETYPE r,D3DFORMAT q){using F=HRESULT(STDMETHODCALLTYPE*)(IDirect3D9*,UINT,D3DDEVTYPE,D3DFORMAT,DWORD,D3DRESOURCETYPE,D3DFORMAT);auto hr=reinterpret_cast<F>(original[10])(p,a,t,f,u,r,q);log("CheckDeviceFormat a=%u f=%u usage=%x resource=%u query=%u hr=%08x caller=%p",a,f,u,r,q,hr,_ReturnAddress());return hr;}
static UINT STDMETHODCALLTYPE modes(IDirect3D9* p,UINT a,D3DFORMAT f){using F=UINT(STDMETHODCALLTYPE*)(IDirect3D9*,UINT,D3DFORMAT);auto n=reinterpret_cast<F>(original[6])(p,a,f);log("ModeCount a=%u f=%u n=%u caller=%p",a,f,n,_ReturnAddress());return n;}
static HRESULT STDMETHODCALLTYPE display(IDirect3D9* p,UINT a,D3DDISPLAYMODE* m){using F=HRESULT(STDMETHODCALLTYPE*)(IDirect3D9*,UINT,D3DDISPLAYMODE*);auto hr=reinterpret_cast<F>(original[8])(p,a,m);log("DisplayMode a=%u hr=%08x %ux%u f=%u hz=%u",a,hr,SUCCEEDED(hr)?m->Width:0,SUCCEEDED(hr)?m->Height:0,SUCCEEDED(hr)?m->Format:0,SUCCEEDED(hr)?m->RefreshRate:0);return hr;}
static HRESULT STDMETHODCALLTYPE texture(IDirect3DDevice9* p,UINT w,UINT h,UINT n,DWORD u,D3DFORMAT f,D3DPOOL pool,IDirect3DTexture9** o,HANDLE* handle){using F=HRESULT(STDMETHODCALLTYPE*)(IDirect3DDevice9*,UINT,UINT,UINT,DWORD,D3DFORMAT,D3DPOOL,IDirect3DTexture9**,HANDLE*);auto hr=reinterpret_cast<F>(deviceOriginal[23])(p,w,h,n,u,f,pool,o,handle);if(FAILED(hr))log("CreateTexture %ux%u f=%u usage=%x pool=%u hr=%08x caller=%p",w,h,f,u,pool,hr,_ReturnAddress());return hr;}
static HRESULT STDMETHODCALLTYPE depth(IDirect3DDevice9* p,UINT w,UINT h,D3DFORMAT f,D3DMULTISAMPLE_TYPE ms,DWORD quality,BOOL discard,IDirect3DSurface9** o,HANDLE* handle){using F=HRESULT(STDMETHODCALLTYPE*)(IDirect3DDevice9*,UINT,UINT,D3DFORMAT,D3DMULTISAMPLE_TYPE,DWORD,BOOL,IDirect3DSurface9**,HANDLE*);auto hr=reinterpret_cast<F>(deviceOriginal[29])(p,w,h,f,ms,quality,discard,o,handle);log("CreateDepth %ux%u f=%u ms=%u hr=%08x caller=%p",w,h,f,ms,hr,_ReturnAddress());return hr;}
static HRESULT STDMETHODCALLTYPE target(IDirect3DDevice9* p,UINT w,UINT h,D3DFORMAT f,D3DMULTISAMPLE_TYPE ms,DWORD quality,BOOL lock,IDirect3DSurface9** o,HANDLE* handle){using F=HRESULT(STDMETHODCALLTYPE*)(IDirect3DDevice9*,UINT,UINT,D3DFORMAT,D3DMULTISAMPLE_TYPE,DWORD,BOOL,IDirect3DSurface9**,HANDLE*);auto hr=reinterpret_cast<F>(deviceOriginal[28])(p,w,h,f,ms,quality,lock,o,handle);log("CreateTarget %ux%u f=%u ms=%u hr=%08x caller=%p",w,h,f,ms,hr,_ReturnAddress());return hr;}
static HRESULT STDMETHODCALLTYPE create(IDirect3D9* p,UINT a,D3DDEVTYPE t,HWND h,DWORD flags,D3DPRESENT_PARAMETERS* q,IDirect3DDevice9** o){using F=HRESULT(STDMETHODCALLTYPE*)(IDirect3D9*,UINT,D3DDEVTYPE,HWND,DWORD,D3DPRESENT_PARAMETERS*,IDirect3DDevice9**);log("CreateDevice a=%u type=%u flags=%x %ux%u f=%u count=%u ms=%u quality=%u swap=%u windowed=%u autodepth=%u depth=%u pflags=%x hz=%u interval=%x caller=%p",a,t,flags,q->BackBufferWidth,q->BackBufferHeight,q->BackBufferFormat,q->BackBufferCount,q->MultiSampleType,q->MultiSampleQuality,q->SwapEffect,q->Windowed,q->EnableAutoDepthStencil,q->AutoDepthStencilFormat,q->Flags,q->FullScreen_RefreshRateInHz,q->PresentationInterval,_ReturnAddress());auto hr=reinterpret_cast<F>(original[16])(p,a,t,h,flags,q,o);log("CreateDevice hr=%08x ptr=%p",hr,SUCCEEDED(hr)?*o:nullptr);if(SUCCEEDED(hr)&&*o){deviceOriginal=*reinterpret_cast<void***>(*o);auto v=new void*[119];memcpy(v,deviceOriginal,119*sizeof(void*));v[23]=reinterpret_cast<void*>(&texture);v[28]=reinterpret_cast<void*>(&target);v[29]=reinterpret_cast<void*>(&depth);*reinterpret_cast<void***>(*o)=v;}return hr;}
extern "C" __declspec(dllexport) IDirect3D9* WINAPI Direct3DCreate9(UINT version){log("Direct3DCreate9 version=%u",version);auto fn=systemMake();auto p=fn?fn(version):nullptr;if(p){original=*reinterpret_cast<void***>(p);auto v=new void*[17];memcpy(v,original,17*sizeof(void*));v[6]=reinterpret_cast<void*>(&modes);v[8]=reinterpret_cast<void*>(&display);v[9]=reinterpret_cast<void*>(&type);v[10]=reinterpret_cast<void*>(&format);v[14]=reinterpret_cast<void*>(&caps);v[16]=reinterpret_cast<void*>(&create);*reinterpret_cast<void***>(p)=v;}return p;}
