'use strict';
const CONFIG=__CONFIG__;const hooks=new Set(),listeners=[],algs=new Map(),props=new Map(),keys=new Map(),seen=new Set();let obs=null,active=true,events=0,caps=0;
function event(code,details={}){if(events++<250)send({kind:'event',code,details});}
function hex(buf){return Array.from(new Uint8Array(buf)).map(x=>x.toString(16).padStart(2,'0')).join('');}
function safe(p,n,max=8192){if(p.isNull()||!n||n>max)return null;try{return hex(p.readByteArray(n));}catch(_){return null;}}
function loc(p){const m=Process.findModuleByAddress(p);return m?{module:m.name,rva:p.sub(m.base).toString()}:{module:null,address:p.toString()};}
function auth(pi){try{if(pi.isNull())return null;const cb=pi.readU32(),v=pi.add(4).readU32();if(cb<80||cb>128)return null;const np=pi.add(8).readPointer(),nl=pi.add(16).readU32(),ap=pi.add(24).readPointer(),al=pi.add(32).readU32(),tp=pi.add(40).readPointer(),tl=pi.add(48).readU32(),mp=pi.add(56).readPointer(),ml=pi.add(64).readU32();return{cbSize:cb,version:v,nonceHex:safe(np,nl,256),nonceBytes:nl,authDataHex:safe(ap,al,8192),authDataBytes:al,tagHex:safe(tp,tl,256),tagBytes:tl,macContextHex:safe(mp,ml,512),macContextBytes:ml,cbAAD:pi.add(68).readU32(),cbData:pi.add(72).readU64().toString(),flags:pi.add(80).readU32()};}catch(_){return null;}}
function attach(m){if(m.name.toLowerCase()!=='bcrypt.dll'||hooks.has(m.base.toString()))return;hooks.add(m.base.toString());
 const open=m.findExportByName('BCryptOpenAlgorithmProvider'),setp=m.findExportByName('BCryptSetProperty'),gen=m.findExportByName('BCryptGenerateSymmetricKey'),destroy=m.findExportByName('BCryptDestroyKey'),dec=m.findExportByName('BCryptDecrypt');
 if(open)listeners.push(Interceptor.attach(open,{onEnter(a){this.out=a[0];try{this.name=a[1].readUtf16String();}catch(_){this.name='?';}},onLeave(s){try{if(s.toUInt32()===0)algs.set(this.out.readPointer().toString(),this.name);}catch(_){}}}));
 if(setp)listeners.push(Interceptor.attach(setp,{onEnter(a){try{const h=a[0].toString(),name=a[1].readUtf16String(),n=a[3].toUInt32();let txt=null;try{txt=a[2].readUtf16String(Math.floor(n/2));}catch(_){};props.set(h+':'+name,{name,text:txt,hex:safe(a[2],n,512)});}catch(_){}}}));
 if(gen)listeners.push(Interceptor.attach(gen,{onEnter(a){this.alg=a[0].toString();this.out=a[1];const n=a[5].toUInt32();this.secret=n>0&&n<=256?safe(a[4],n,256):null;this.n=n;},onLeave(s){try{if(s.toUInt32()===0&&this.secret){const h=this.out.readPointer().toString();const mode=props.get(this.alg+':ChainingMode');keys.set(h,{algorithm:algs.get(this.alg)||'?',chainingMode:mode&&mode.text||null,secretHex:this.secret,secretBytes:this.n});}}catch(_){}}}));
 if(destroy)listeners.push(Interceptor.attach(destroy,{onEnter(a){keys.delete(a[0].toString());}}));
 if(!dec){event('NO_BCRYPT_DECRYPT');return;}
 listeners.push(Interceptor.attach(dec,{onEnter(a){this.hit=null;if(!active||caps>=30)return;try{const n=a[2].toUInt32();if(n<6)return;const pref=hex(a[1].readByteArray(6)),expect=CONFIG.prefixes[pref];if(expect===undefined||expect!==n)return;const full=a[1].readByteArray(n),digest=Checksum.compute('sha256',full),uniq=pref+':'+digest;if(seen.has(uniq))return;this.hit={prefix:pref,inputSha256:digest,inputBytes:n,caller:loc(this.returnAddress),flags:a[9].toUInt32(),key:keys.get(a[0].toString())||null,auth:auth(a[3]),ivHex:safe(a[4],a[5].toUInt32(),256)};this.output=a[6];this.cap=a[7].toUInt32();this.result=a[8];}catch(e){event('MATCH_ERROR',{message:String(e).slice(0,220)});}},onLeave(s){if(!this.hit)return;try{const st=s.toUInt32();if(st!==0){event('MATCH_FAIL',{status:'0x'+st.toString(16)});return;}seen.add(this.hit.prefix+':'+this.hit.inputSha256);let bytes=null,n=0;if(!this.output.isNull()&&!this.result.isNull()){n=this.result.readU32();if(n>0&&n<=this.cap&&n<=8*1024*1024)bytes=this.output.readByteArray(n);}this.hit.kind='resource';this.hit.outputBytes=n;this.hit.outputSha256=bytes?Checksum.compute('sha256',bytes):null;caps++;send(this.hit,bytes);}catch(e){event('OUTPUT_ERROR',{message:String(e).slice(0,220)});}}}));
 event('HOOK_READY',{targets:Object.keys(CONFIG.prefixes).length});}
if(Process.platform!=='windows'||Process.arch!=='x64')throw new Error('Windows x64 requerido');obs=Process.attachModuleObserver({onAdded(m){try{attach(m);}catch(e){event('HOOK_ERROR',{message:String(e).slice(0,220)});}}});rpc.exports={stop(){active=false;for(const h of listeners)try{h.detach();}catch(_){};if(obs)try{obs.detach();}catch(_){};return{caps};}};event('READY',{scope:'exact-SPK-resource-ciphertexts-only'});