import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:path_provider/path_provider.dart';
import 'package:three_js/three_js.dart' as three;
import 'data/catalog.dart';
import 'data/library.dart';
import 'render/studio_scene.dart';

void main(){WidgetsFlutterBinding.ensureInitialized();runApp(const ShaiyaApp());}
class ShaiyaApp extends StatelessWidget {
  const ShaiyaApp({super.key});
  @override Widget build(BuildContext context)=>MaterialApp(
    debugShowCheckedModeBanner:false,title:'Herramienta Shaiya',locale:const Locale('es'),
    supportedLocales:const [Locale('es')],localizationsDelegates:GlobalMaterialLocalizations.delegates,
    theme:ThemeData(brightness:Brightness.dark,useMaterial3:true,scaffoldBackgroundColor:const Color(0xff0f131b),colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xff8b9cf6),brightness:Brightness.dark),fontFamily:'Segoe UI',
      inputDecorationTheme:const InputDecorationTheme(isDense:true,border:OutlineInputBorder(),contentPadding:EdgeInsets.symmetric(horizontal:12,vertical:13)),
      cardTheme:const CardThemeData(color:Color(0xff171e2b),elevation:0,margin:EdgeInsets.zero)),
    home:const StudioPage());
}
class StudioPage extends StatefulWidget {const StudioPage({super.key});@override State<StudioPage> createState()=>_StudioState();}
class _StudioState extends State<StudioPage> {
  late final StudioScene scene;
  late final three.ThreeJS renderer;
  Catalog? catalog;
  int tab=0;
  bool importing=false,working=false;
  String progress='Selecciona DATA para comenzar.';
  final List<String> diagnostics=[];
  final captureKey=GlobalKey();
  final focus=FocusNode();
  double gestureScale=1;
  final xController=TextEditingController(),zController=TextEditingController();
  @override void initState(){super.initState();scene=StudioScene(log);renderer=three.ThreeJS(
    settings:three.Settings(clearColor:0x11151e,antialias:true,enableShadowMap:false,toneMapping:three.NoToneMapping),
    setup:()=>scene.setup(renderer),onSetupComplete:(){if(mounted)setState((){});});scene.addListener(refresh);}
  void refresh(){if(mounted)setState((){});}
  void log(String value){diagnostics.insert(0,'${DateTime.now().toIso8601String()} · $value');if(diagnostics.length>300)diagnostics.removeLast();}
  Future<void> act(Future<void> Function() action) async {
    if(working||importing)return;setState(()=>working=true);
    try{await action();}catch(e,stack){log('$e\n$stack');if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString()),duration:const Duration(seconds:7)));}
    finally{if(mounted)setState(()=>working=false);}
  }
  Future<void> connect() async {
    if(importing||working)return;setState(()=>importing=true);
    final old=scene.catalog;
    try {
      final lib=await Library.choose((s){if(mounted)setState(()=>progress=s);});if(lib==null)return;
      final next=Catalog(lib);await next.load((s){if(mounted)setState(()=>progress=s);});
      if(!mounted)return;
      scene.catalog=next;
      final first=next.archetypes.where((a)=>a.id=='humf').firstOrNull??next.archetypes.first;
      await scene.setAppearance(Appearance.initial(first));
      catalog=next;diagnostics.addAll(next.warnings);scene.combat.reset();
      await scene.selectCreature(null,'enemy');await scene.selectCreature(null,'mount');await scene.selectCreature(null,'wing');await scene.setWorld(null);
      progress='${lib.files.length} recursos indexados · solo lectura';
    }catch(e,stack){if(catalog!=scene.catalog)scene.catalog=old;log('$e\n$stack');progress='No se pudo conectar la biblioteca: $e';if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(progress)));}
    finally{if(mounted)setState(()=>importing=false);}
  }
  @override void dispose(){scene.removeListener(refresh);scene.dispose();renderer.dispose();focus.dispose();xController.dispose();zController.dispose();super.dispose();}
  bool get disabled=>working||importing||!scene.ready;
  Future<T?> choose<T>(String title,List<T> values,String Function(T) label,{String Function(T)? detail}) async {
    return showDialog<T>(context:context,builder:(ctx){var query='';return StatefulBuilder(builder:(ctx,setDialog){final filtered=values.where((v)=>'${label(v)} ${detail?.call(v)??''}'.toLowerCase().contains(query.toLowerCase())).toList();return AlertDialog(title:Text(title),content:SizedBox(width:560,height:440,child:Column(children:[TextField(autofocus:true,decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'Buscar por nombre, número o archivo'),onChanged:(s)=>setDialog(()=>query=s)),const SizedBox(height:12),Align(alignment:Alignment.centerLeft,child:Text('${filtered.length} resultados',style:Theme.of(ctx).textTheme.labelSmall)),Expanded(child:ListView.builder(itemCount:filtered.length,itemBuilder:(ctx,i){final v=filtered[i];return ListTile(dense:true,title:Text(label(v)),subtitle:detail==null?null:Text(detail(v),maxLines:2,overflow:TextOverflow.ellipsis),onTap:()=>Navigator.pop(ctx,v));}))])),actions:[TextButton(onPressed:()=>Navigator.pop(ctx),child:const Text('Cancelar'))]);});});
  }
  Widget section(String title,{String? text,required List<Widget> children})=>Padding(padding:const EdgeInsets.only(bottom:24),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text(title,style:const TextStyle(fontSize:17,fontWeight:FontWeight.w600)),if(text!=null)Padding(padding:const EdgeInsets.only(top:7,bottom:10),child:Text(text,style:const TextStyle(fontSize:12,color:Color(0xffa1acbe),height:1.55))),const SizedBox(height:8),...children]));
  Widget pickButton(String label,String value,VoidCallback? tap,{IconData icon=Icons.chevron_right})=>Padding(padding:const EdgeInsets.only(bottom:9),child:OutlinedButton(onPressed:disabled?null:tap,style:OutlinedButton.styleFrom(padding:const EdgeInsets.symmetric(horizontal:12,vertical:13),alignment:Alignment.centerLeft,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(8))),child:Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(label,style:const TextStyle(fontSize:11,color:Color(0xff9aa6bd))),const SizedBox(height:4),Text(value,maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:13,color:Color(0xffe4e7f1)))])),Icon(icon,size:18)])));
  Widget slider(String title,double value,double min,double max,void Function(double) change)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(title,style:const TextStyle(fontSize:12))),Text(value.toStringAsFixed(2),style:const TextStyle(fontSize:11))]),Slider(value:value.clamp(min,max),min:min,max:max,onChanged:disabled?null:change)]);
  Widget note(String value)=>Padding(padding:const EdgeInsets.symmetric(vertical:8),child:Text(value,style:const TextStyle(fontSize:11,color:Color(0xffa5b1c6),height:1.55)));
  Widget panel(){
    if(catalog==null)return section('Biblioteca local',text:'Conecta DATA o su carpeta contenedora. Los modelos, texturas y sonidos se leen en tu equipo; no se modifican ni se suben.',children:[FilledButton.icon(onPressed:disabled?null:connect,icon:const Icon(Icons.folder_open),label:const Text('Seleccionar DATA')),note(progress),note('Esta aplicación es Flutter nativo. No abre un navegador ni incorpora el visor HTML.')]);
    final c=catalog!,a=scene.appearance?.archetype,look=scene.appearance;
    if(a==null||look==null)return Text(progress);
    switch(tab){
      case 0:return Column(children:[section('Personaje',text:'Cada arquetipo conserva sus propias mallas, texturas y animaciones.',children:[
        pickButton('Raza',raceLabels[a.race]??a.race,()=>act(() async {final races=c.archetypes.map((a)=>a.race).toSet().toList();final race=await choose('Elegir raza',races,(s)=>raceLabels[s]??s);if(race!=null)await scene.setAppearance(Appearance.initial(c.archetypes.firstWhere((a)=>a.race==race)));})),
        pickButton('Cuerpo / arquetipo',a.label,()=>act(()async{final next=await choose('Arquetipos',c.archetypes.where((x)=>x.race==a.race).toList(),(v)=>v.label);if(next!=null)await scene.setAppearance(Appearance.initial(next));})),
        for(final s in [Slot.face,Slot.hair])pickButton(slotLabels[s]!,look.selected[s]?.label??'Sin selección',()=>selectPart(s)),
        Row(children:[Expanded(child:OutlinedButton(onPressed:disabled?null:()=>act(saveAppearance),child:const Text('Guardar'))),const SizedBox(width:8),Expanded(child:OutlinedButton(onPressed:disabled?null:()=>act(loadAppearance),child:const Text('Recuperar')))]),
        note('Los identificadores de archivo se mantienen en su idioma original para poder localizar exactamente cada recurso.')]),
        section('Cuerpo base',text:'Retirar equipo restablece la pieza base de ese arquetipo. Solo se identifica como desnudo un recurso original expresamente verificado; body001 también puede ser una armadura.',children:[OutlinedButton.icon(onPressed:disabled?null:()=>act(() async {final n=Appearance(a,{for(final s in Slot.values)s:([Slot.face,Slot.hair].contains(s)?look.selected[s]:null)});await scene.setAppearance(n);}),icon:const Icon(Icons.accessibility_new),label:const Text('Restablecer equipo base'))])]);
      case 1:return Column(children:[section('Atuendos y armaduras',text:'Aplicación atómica: el conjunto nuevo reemplaza todas las piezas anteriores. Los trajes integrales no heredan el pantalón del último set.',children:[pickButton('Conjunto completo','Elegir entre ${a.sets.length} conjuntos',()=>act(()async{final id=await choose('Conjuntos',a.sets.keys.toList(),displaySet,detail:(key)=>a.sets[key]!.values.map((p)=>p.raw.texture).join(' · '));if(id!=null)await scene.setAppearance(Appearance.forSet(a,id,previous:look));})),for(final s in [Slot.upper,Slot.lower,Slot.hand,Slot.foot,Slot.helmet])Row(children:[Expanded(child:pickButton(slotLabels[s]!,look.selected[s]?.label??(s==Slot.helmet?'Sin casco':'Base / cubierta por traje'),()=>selectPart(s))),IconButton(tooltip:'Retirar y restaurar base',onPressed:disabled?null:()=>act(()=>scene.setAppearance(look.withPart(s,null))),icon:const Icon(Icons.remove_circle_outline,size:19))])]),
        section('Arma',text:'Se utilizan las posiciones y rotaciones IT2 asociadas al arquetipo. Una combinación sin anclaje válido se rechaza; no se coloca el arma al azar.',children:[pickButton('Arma equipada',scene.weaponRecord==null?'Ninguna':'${scene.weaponRecord!.source} · ${scene.weaponRecord!.id}',()=>act(()async{final w=await choose('Elegir arma',c.weapons,(w)=>'Arma ${w.id} · familia ${baseName(w.source).replaceFirst('.itm','')}',detail:(w)=>'${w.mesh}\n${w.texture}');if(w!=null)await scene.equip(w);})),TextButton(onPressed:disabled?null:()=>act(()=>scene.equip(null)),child:const Text('Quitar arma')),note('Los recursos que no pueden interpretarse aparecen en Diagnóstico y no se sustituyen por armas inventadas.')])]);
      case 2:return Column(children:[section('Alas',text:'Mallas y animaciones del catálogo original Wing.MON. Ajustes de encaje disponibles para distintas anatomías.',children:[pickButton('Alas',scene.wingRecord==null?'Sin alas':c.creatureLabel(scene.wingRecord!),()=>pickCreature('wing')),TextButton(onPressed:disabled?null:()=>act(()=>scene.selectCreature(null,'wing')),child:const Text('Quitar alas')),if(scene.wing!=null)...[actorAnimations(scene.wing!,'wing'),slider('Altura en la espalda',scene.wingHeight,-2,4,(x)=>setState(()=>scene.wingHeight=x)),slider('Separación de la espalda',scene.wingDepth,-2,2,(x)=>setState(()=>scene.wingDepth=x)),slider('Escala de las alas',scene.wingSize,.1,3,(x)=>setState(()=>scene.wingSize=x))]]),section('Monturas',text:'Vista previa del jinete y su montura. El encaje puede requerir ajuste manual; no se considera calibrado para todas las combinaciones.',children:[pickButton('Montura',scene.mountRecord==null?'A pie':c.creatureLabel(scene.mountRecord!),()=>pickCreature('mount')),TextButton(onPressed:disabled?null:()=>act(()=>scene.selectCreature(null,'mount')),child:const Text('Desmontar')),if(scene.mount!=null)...[actorAnimations(scene.mount!,'mount'),slider('Altura del jinete',scene.riderHeight,0,6,(x)=>setState(()=>scene.riderHeight=x)),slider('Posición de la montura',scene.riderForward,-3,3,(x)=>setState(()=>scene.riderForward=x)),note('Se selecciona una animación de montar compatible cuando existe en el arquetipo. El desplazamiento del laboratorio no reproduce la física de cada vehículo.')]])]);
      case 3:return Column(children:[section('Pruebas de combate',text:'Simulación local con daño y tiempos configurables; no reproduce las reglas del servidor ni altera los archivos del juego.',children:[pickButton('Oponente',scene.enemyRecord==null?'Elegir una criatura':c.creatureLabel(scene.enemyRecord!),()=>pickCreature('enemy')),if(scene.enemy!=null)actorAnimations(scene.enemy!,'enemy'),health('Personaje',scene.combat.playerHealth),health('Criatura',scene.combat.enemyHealth),const SizedBox(height:10),Row(children:[Expanded(child:FilledButton.icon(onPressed:disabled||scene.enemy==null?null:()=>act(scene.attack),icon:const Icon(Icons.flash_on),label:const Text('Atacar'))),const SizedBox(width:8),OutlinedButton(onPressed:scene.resetCombat,child:const Text('Reiniciar'))]),SwitchListTile(contentPadding:EdgeInsets.zero,dense:true,title:const Text('Ataque automático'),value:scene.combat.automatic,onChanged:scene.enemy==null||scene.mount!=null?null:(v){setState(()=>scene.combat.automatic=v);if(v)act(scene.attack);}),SwitchListTile(contentPadding:EdgeInsets.zero,dense:true,title:const Text('La criatura contraataca'),value:scene.combat.counterattack,onChanged:(v)=>setState(()=>scene.combat.counterattack=v)),slider('Daño del personaje',scene.combat.damage,10,250,(v)=>setState(()=>scene.combat.damage=v)),slider('Daño de la criatura',scene.combat.enemyDamage,10,150,(v)=>setState(()=>scene.combat.enemyDamage=v)),slider('Alcance de la prueba',scene.combat.range,1,12,(v)=>setState(()=>scene.combat.range=v)),if(scene.enemy!=null)slider('Separación del oponente',scene.enemy!.root.position.x,.5,10,(v)=>setState(()=>scene.enemy!.root.position.x=v)),note(scene.combat.log.take(7).join('\n'))]),
        section('Efectos y audio',text:'Las texturas y sonidos son originales. La secuencia visual de impacto es una simulación del laboratorio; no se ha implementado el intérprete completo de EFT.',children:[SwitchListTile(contentPadding:EdgeInsets.zero,title:const Text('Activar sonido'),subtitle:const Text('Permite los sonidos asociados a la criatura'),value:scene.sound,onChanged:(v)=>setState(()=>scene.sound=v)),pickButton('Efecto de impacto',scene.effectPath==null?'Sin textura':baseName(scene.effectPath!),()=>act(()async{final p=await choose('Texturas de efectos',c.effects,baseName,detail:(s)=>s);if(p!=null)await scene.setEffect(p);})),pickButton('Escuchar un recurso','Explorar ${c.sounds.length} sonidos',()=>act(()async{final p=await choose('Sonidos originales',c.sounds,baseName,detail:(s)=>s);if(p!=null){scene.sound=true;await scene.playSound(p);}}))])]);
      case 4:return Column(children:[section('Mapas y terreno',text:'Sectores exteriores WLD con alturas, materiales y objetos originales. Se carga un área de 128 × 128 m para limitar el uso de memoria.',children:[pickButton('Escenario',scene.worldPath==null?'Estudio neutro':baseName(scene.worldPath!),()=>act(()async{final path=await choose('Mapas WLD',c.worlds,(s)=>'Mapa ${baseName(s).replaceFirst('.wld','')}',detail:(s)=>s);if(path!=null)await scene.setWorld(path);})),OutlinedButton(onPressed:disabled?null:()=>act(()=>scene.setWorld(null)),child:const Text('Volver al estudio')),const SizedBox(height:14),Row(children:[Expanded(child:TextField(controller:xController,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Coordenada X'))),const SizedBox(width:8),Expanded(child:TextField(controller:zController,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Coordenada Z')))]),const SizedBox(height:8),FilledButton.tonal(onPressed:disabled||scene.worldPath==null?null:()=>act(()async{final x=double.tryParse(xController.text),z=double.tryParse(zController.text);if(x==null||z==null)throw const FormatException('Introduce coordenadas numéricas.');await scene.setWorld(scene.worldPath,x:x,z:z);}),child:const Text('Cargar sector')),note('Posición del sector: ${scene.originX.toStringAsFixed(0)}, ${scene.originZ.toStringAsFixed(0)}\nNo hay colisión con edificios. Mazmorras DG, agua, zonas y mezcla avanzada de capas aún no están implementadas.')]),section('Presentación',children:[SwitchListTile(contentPadding:EdgeInsets.zero,title:const Text('Mostrar malla'),value:scene.wireframe,onChanged:scene.setWireframe),slider('Distancia de cámara',scene.distance,.4,35,(v){scene.distance=v;scene.updateCamera();}),slider('Altura del encuadre',scene.targetY,-1,5,(v){scene.targetY=v;scene.updateCamera();}),FilledButton.tonalIcon(onPressed:()=>act(capture),icon:const Icon(Icons.photo_camera_outlined),label:const Text('Guardar captura PNG')),note('Materiales de color original sin mapeo tonal. Evita interpretar un canal de brillo como un agujero transparente o aplicar una iluminación físicamente incorrecta a texturas pintadas.')])]);
      default:return Column(children:[section('Diagnóstico',text:'Los recursos incompatibles se identifican por ruta; no se sustituyen silenciosamente por una malla o una textura negra.',children:[Text('${c.library.files.length} recursos\n${c.archetypes.length} arquetipos\n${c.weapons.length} registros de armas\n${c.creatures.length} registros de criaturas\n${c.mounts.length} registros de monturas (puede haber variantes repetidas)\n${c.wings.length} registros de alas\n${c.worlds.length} mapas',style:const TextStyle(height:1.8)),const SizedBox(height:14),OutlinedButton(onPressed:()=>act(exportDiagnostics),child:const Text('Exportar diagnóstico JSON')),note('Formatos activos: 3DC, ANI, MLT, ITM/IT2, MON, DDS, 3DO, WLD exterior y SMOD.\nLas opciones ofrecidas son registros localizados: no equivalen a todas las combinaciones visualmente validadas.\nLectura nativa, sin HTML, sin WebView, sin subida de DATA.')]),SelectableText(diagnostics.take(40).join('\n\n'),style:const TextStyle(fontSize:11,height:1.5))]);
    }
  }
  void selectPart(Slot s)=>act(()async{final a=scene.appearance!.archetype;final p=await choose(slotLabels[s]!,a.parts[s]??[],(p)=>p.label,detail:(p)=>'${p.raw.mesh}\n${p.raw.texture}');if(p!=null)await scene.setAppearance(scene.appearance!.withPart(s,p));});
  void pickCreature(String kind)=>act(()async{final c=catalog!,list=kind=='enemy'?c.creatures:kind=='mount'?c.mounts:c.wings;final p=await choose(kind=='enemy'?'Criaturas':kind=='mount'?'Monturas':'Alas',list,c.creatureLabel,detail:(v)=>v.parts.map((p)=>p.mesh).join(' · '));if(p!=null)await scene.selectCreature(p,kind);});
  Widget actorAnimations(Actor a,String target)=>pickButton('Animación','${a.clips.length} clips disponibles',()=>act(()async{final key=await choose('Animaciones',a.clips.keys.toList(),(s)=>s);if(key!=null)await scene.previewActorAnimation(target,key);}));
  Widget health(String name,double hp)=>Padding(padding:const EdgeInsets.only(top:10),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Row(children:[Expanded(child:Text(name,style:const TextStyle(fontSize:12))),Text('${hp.round()} / ${scene.combat.maxHealth.round()}',style:const TextStyle(fontSize:11))]),const SizedBox(height:5),LinearProgressIndicator(value:(hp/scene.combat.maxHealth).clamp(0.0,1.0),minHeight:6,borderRadius:BorderRadius.circular(8))]));
  Future<File> saveFile(String name,String content) async {final dir=await getApplicationDocumentsDirectory();final folder=Directory('${dir.path}/HerramientaShaiya');await folder.create(recursive:true);final f=File('${folder.path}/$name');await f.writeAsString(content,flush:true);scene.say('Guardado: ${f.path}');return f;}
  Future<void> saveAppearance() async {final look=scene.appearance!;await saveFile('apariencia.json',jsonEncode({'version':1,'archetype':look.archetype.id,'race':look.archetype.race,'fullCostume':look.fullCostume,'slots':{for(final e in look.selected.entries)e.key.name:e.value?.raw.id}}));}
  Future<void> loadAppearance() async {final d=await getApplicationDocumentsDirectory();final f=File('${d.path}/HerramientaShaiya/apariencia.json');if(!await f.exists())throw const FormatException('No hay una apariencia guardada.');final data=jsonDecode(await f.readAsString()) as Map;final a=catalog!.archetypes.where((a)=>a.id==data['archetype']&&a.race==data['race']).firstOrNull;if(a==null)throw const FormatException('El arquetipo guardado no existe en DATA.');final slots=<Slot,PartRecord?>{};for(final s in Slot.values){final id=(data['slots'] as Map)[s.name];slots[s]=id==null?null:a.parts[s]!.where((p)=>p.raw.id==id).firstOrNull;if(id!=null&&slots[s]==null)throw FormatException('La pieza guardada ${s.name} #$id ya no existe.');}await scene.setAppearance(Appearance(a,slots,fullCostume:data['fullCostume']==true));}
  Future<void> exportDiagnostics() async {await saveFile('diagnostico.json',const JsonEncoder.withIndent('  ').convert({'version':'0.1.0','time':DateTime.now().toIso8601String(),'platform':Platform.operatingSystem,'resources':catalog?.library.files.length,'messages':diagnostics}));}
  Future<void> capture() async {final boundary=captureKey.currentContext?.findRenderObject() as RenderRepaintBoundary?;if(boundary==null)return;final im=await boundary.toImage(pixelRatio:1.5);final bytes=await im.toByteData(format:ui.ImageByteFormat.png);im.dispose();if(bytes==null)throw const FormatException('No se pudo capturar el visor.');final dir=await getApplicationDocumentsDirectory();final f=File('${dir.path}/Shaiya_${DateTime.now().millisecondsSinceEpoch}.png');await f.writeAsBytes(bytes.buffer.asUint8List());scene.say('Captura guardada: ${f.path}');}
  Widget navigation(bool compact)=>compact?DropdownButton<int>(value:tab,isExpanded:true,items:List.generate(labels.length,(i)=>DropdownMenuItem(value:i,child:Row(children:[Icon(icons[i],size:18),const SizedBox(width:10),Text(labels[i])]))),onChanged:(v)=>setState(()=>tab=v!)):NavigationRail(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),labelType:NavigationRailLabelType.all,minWidth:90,backgroundColor:const Color(0xff121824),destinations:List.generate(labels.length,(i)=>NavigationRailDestination(icon:Icon(icons[i]),label:Text(labels[i],style:const TextStyle(fontSize:11)))));
  static const labels=['Personaje','Equipo','Alas y monturas','Combate','Escenario','Diagnóstico'];
  static const icons=[Icons.person_outline,Icons.shield_outlined,Icons.pets_outlined,Icons.sports_martial_arts,Icons.landscape_outlined,Icons.fact_check_outlined];
  Widget viewport()=>RepaintBoundary(key:captureKey,child:Stack(children:[Positioned.fill(child:renderer.build()),Positioned.fill(child:Focus(focusNode:focus,onFocusChange:(active){if(!active){scene.walkX=0;scene.walkZ=0;}},onKeyEvent:(node,event){final keys=HardwareKeyboard.instance.logicalKeysPressed;scene.walkX=(keys.contains(LogicalKeyboardKey.keyD)?1.0:0)-(keys.contains(LogicalKeyboardKey.keyA)?1.0:0);scene.walkZ=(keys.contains(LogicalKeyboardKey.keyS)?1.0:0)-(keys.contains(LogicalKeyboardKey.keyW)?1.0:0);return [LogicalKeyboardKey.keyW,LogicalKeyboardKey.keyA,LogicalKeyboardKey.keyS,LogicalKeyboardKey.keyD].contains(event.logicalKey)?KeyEventResult.handled:KeyEventResult.ignored;},child:Listener(onPointerSignal:(event){if(event is PointerScrollEvent)scene.zoom(event.scrollDelta.dy>0?1.08:1/1.08);},child:GestureDetector(behavior:HitTestBehavior.opaque,onTap:focus.requestFocus,onScaleStart:(d){gestureScale=1;focus.requestFocus();},onScaleUpdate:(d){if(d.pointerCount==1){scene.orbit(d.focalPointDelta.dx,d.focalPointDelta.dy);}else{scene.zoom(gestureScale/d.scale);gestureScale=d.scale;}},child:const SizedBox.expand())))),
    Positioned(top:18,left:18,right:18,child:IgnorePointer(child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(scene.appearance?.archetype.label??'Estudio 3D',style:const TextStyle(fontSize:18,fontWeight:FontWeight.w500)),const SizedBox(height:5),const Text('Arrastrar: girar · Rueda / pellizco: zoom · WASD: mover',style:TextStyle(fontSize:11,color:Color(0xffaab3c4)))])),if(scene.character!=null)Text('${scene.character!.parts.fold(0,(n,p)=>n+p.data.triangles)} tris',style:const TextStyle(fontSize:11,color:Color(0xff8994aa)))]))),
    if(catalog==null)Center(child:Container(constraints:const BoxConstraints(maxWidth:410),margin:const EdgeInsets.all(30),padding:const EdgeInsets.all(30),decoration:BoxDecoration(color:const Color(0xff172032),borderRadius:BorderRadius.circular(16),border:Border.all(color:const Color(0xff303d55))),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[const Icon(Icons.view_in_ar,size:35,color:Color(0xffa7b6ff)),const SizedBox(height:24),const Text('Explora tu\nbiblioteca Shaiya.',style:TextStyle(fontSize:34,fontWeight:FontWeight.w500,height:1.15)),const SizedBox(height:16),const Text('Personajes, equipo, criaturas y escenarios originales en un espacio de trabajo nativo.',style:TextStyle(color:Color(0xffaab6cc),height:1.6)),const SizedBox(height:22),FilledButton.icon(onPressed:disabled?null:connect,icon:const Icon(Icons.folder_open),label:const Text('Conectar carpeta DATA'))]))),
    if(scene.character!=null)Positioned(bottom:100,right:18,child:Column(children:[movePad(Icons.arrow_upward,0,-1),Row(children:[movePad(Icons.arrow_back,-1,0),movePad(Icons.arrow_downward,0,1),movePad(Icons.arrow_forward,1,0)])])),
    if(importing||working||scene.busy)Positioned(top:80,left:18,right:18,child:Card(child:Padding(padding:const EdgeInsets.all(14),child:Row(children:[const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)),const SizedBox(width:12),Expanded(child:Text(importing?progress:'Preparando recursos… Se conserva la escena anterior.',style:const TextStyle(fontSize:12)))])))),
    if(scene.character!=null)Positioned(bottom:14,left:14,right:14,child:Card(child:Padding(padding:const EdgeInsets.symmetric(horizontal:12,vertical:8),child:Column(mainAxisSize:MainAxisSize.min,children:[Row(children:[IconButton(tooltip:'Reproducir / Pausar',onPressed:()=>setState(()=>scene.character!.playing=!scene.character!.playing),icon:Icon(scene.character!.playing?Icons.pause:Icons.play_arrow)),Expanded(child:TextButton(onPressed:disabled?null:()=>act(()async{final p=await choose('Animaciones del personaje',scene.animations,animationLabel,detail:(s)=>baseName(s));if(p!=null)await scene.selectAnimation(p);}),child:Text(scene.character!.clip==null?'Sin animación':animationLabel(scene.character!.clip!.source),maxLines:1,overflow:TextOverflow.ellipsis))),DropdownButton<double>(value:scene.character!.speed,items:[.25,.5,1.0,1.5,2.0].map((v)=>DropdownMenuItem(value:v,child:Text('$v×',style:const TextStyle(fontSize:11)))).toList(),onChanged:(v)=>setState(()=>scene.character!.speed=v!))]),Slider(value:scene.character!.clip==null?0:((scene.character!.time%scene.character!.clip!.duration)/scene.character!.clip!.duration).clamp(0.0,1.0),onChanged:scene.character!.clip==null?null:(v){scene.character!.time=v*scene.character!.clip!.duration;scene.character!.playing=false;scene.character!.pose();setState((){});})]))))]));
  Widget movePad(IconData icon,double x,double z)=>Listener(onPointerDown:(_){scene.walkX=x;scene.walkZ=z;},onPointerUp:(_){scene.walkX=scene.walkZ=0;},onPointerCancel:(_){scene.walkX=scene.walkZ=0;},child:Container(margin:const EdgeInsets.all(2),width:34,height:32,decoration:BoxDecoration(color:const Color(0xbb232d40),borderRadius:BorderRadius.circular(6)),child:Icon(icon,size:17)));
  @override Widget build(BuildContext context)=>LayoutBuilder(builder:(ctx,box){final compact=box.maxWidth<900;final controls=SingleChildScrollView(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[if(compact)...[navigation(true),const SizedBox(height:15)],panel()]));return Scaffold(appBar:AppBar(title:Row(children:[const Icon(Icons.layers_outlined,color:Color(0xffaab8ff)),const SizedBox(width:12),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('SHAIYA STUDIO',style:TextStyle(fontSize:16,fontWeight:FontWeight.w600,letterSpacing:1.6)),Text('Laboratorio nativo · Windows / Android',style:TextStyle(fontSize:10,color:Theme.of(context).colorScheme.outline))])]),actions:[if(catalog!=null&&!compact)Center(child:Text('${catalog!.library.files.length} recursos',style:const TextStyle(fontSize:11))),const SizedBox(width:14),TextButton.icon(onPressed:disabled?null:connect,icon:const Icon(Icons.folder_open,size:19),label:const Text('DATA')),const SizedBox(width:10)],backgroundColor:const Color(0xff131a27)),drawer:compact?Drawer(width:340,child:SafeArea(child:controls)):null,body:Column(children:[Expanded(child:Row(children:[if(!compact)...[navigation(false),Container(width:310,decoration:const BoxDecoration(color:Color(0xff171d29),border:Border(right:BorderSide(color:Color(0xff293245)))),child:controls)],Expanded(child:viewport())])),Container(height:32,padding:const EdgeInsets.symmetric(horizontal:16),decoration:const BoxDecoration(color:Color(0xff151c29),border:Border(top:BorderSide(color:Color(0xff2b3548)))),child:Row(children:[const Icon(Icons.lock_outline,size:12,color:Color(0xff90bfa6)),const SizedBox(width:8),Expanded(child:Text(scene.status,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:10,color:Color(0xffaab5c8)))),const Text('0.1 · Desarrollo',style:TextStyle(fontSize:10,color:Color(0xff7e8aa0)))]))]));});
}
