import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:path_provider/path_provider.dart';
import 'package:three_js/three_js.dart' as three;
import 'core/formats.dart';
import 'data/catalog.dart';
import 'data/library.dart';
import 'render/studio_scene.dart';
import 'input/viewport_movement_input.dart';
import 'ui/asset_selector.dart';
import 'ui/studio_workspace.dart';

void main(List<String> args){WidgetsFlutterBinding.ensureInitialized();final data=args.where((x)=>x.startsWith('--data=')).firstOrNull;runApp(ShaiyaApp(initialData:data?.substring(7)));}
class ShaiyaApp extends StatelessWidget {
  final String? initialData;
  const ShaiyaApp({super.key,this.initialData});
  @override Widget build(BuildContext context)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Shaiya Studio',locale:const Locale('es'),supportedLocales:const [Locale('es')],localizationsDelegates:GlobalMaterialLocalizations.delegates,
    theme:ThemeData(brightness:Brightness.dark,useMaterial3:true,visualDensity:VisualDensity.compact,colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xffa5bcff),brightness:Brightness.dark),scaffoldBackgroundColor:const Color(0xff101722),inputDecorationTheme:const InputDecorationTheme(isDense:true,border:OutlineInputBorder(),contentPadding:EdgeInsets.symmetric(horizontal:10,vertical:10)),textTheme:const TextTheme(bodyMedium:TextStyle(fontSize:12),bodySmall:TextStyle(fontSize:10)),sliderTheme:const SliderThemeData(trackHeight:2,thumbShape:RoundSliderThumbShape(enabledThumbRadius:5),overlayShape:RoundSliderOverlayShape(overlayRadius:12)),cardTheme:const CardThemeData(color:Color(0xff192331),elevation:0,margin:EdgeInsets.zero)),home:StudioPage(initialData:initialData));
}
class StudioPage extends StatefulWidget {
  final String? initialData;const StudioPage({super.key,this.initialData});
  @override State<StudioPage> createState()=>_StudioState();
}
class _StudioState extends State<StudioPage> {
  late final StudioScene scene;late final three.ThreeJS renderer;Catalog? catalog;int tab=0;
  bool importing=false,working=false;String progress='Selecciona DATA para comenzar.';
  final List<String> diagnostics=[];final captureKey=GlobalKey();final focus=FocusNode();
  final Map<String,SelectionMemory> _memories={};String inspectorTarget='Personaje',lastSound='';
  double gestureScale=1;final xController=TextEditingController(),zController=TextEditingController();
  @override void initState(){super.initState();scene=StudioScene(log);renderer=three.ThreeJS(settings:three.Settings(clearColor:0x11151e,antialias:true,enableShadowMap:false,toneMapping:three.NoToneMapping),setup:()=>scene.setup(renderer),onSetupComplete:(){if(mounted){setState((){});if(widget.initialData!=null)connect(path:widget.initialData);}});scene.addListener(refresh);}
  void refresh(){if(mounted)setState((){});}
  void log(String value){diagnostics.insert(0,'${DateTime.now().toIso8601String()} · $value');if(diagnostics.length>300)diagnostics.removeLast();}
  void showError(Object e){log(e.toString());if(mounted){ScaffoldMessenger.of(context).hideCurrentSnackBar();ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString()),duration:const Duration(seconds:5)));}}
  Future<void> act(Future<void> Function() action,{bool restoreFocus=false}) async {if(working||importing)return;scene.clearMovement();setState(()=>working=true);try{await action();}catch(e){showError(e);}finally{if(mounted){setState(()=>working=false);if(restoreFocus)focus.requestFocus();}}}
  Future<void> connect({String? path}) async {
    if(importing||working)return;scene.clearMovement();setState(()=>importing=true);final old=scene.catalog;
    try{void report(String s){if(mounted)setState(()=>progress=s);}final lib=path==null?await Library.choose(report):await Library.fromDirectory(path,report);if(lib==null)return;final next=Catalog(lib);await next.load(report);if(!mounted)return;scene.catalog=next;final first=next.archetypes.where((a)=>a.id=='humf').firstOrNull??next.archetypes.first;await scene.setAppearance(Appearance.initial(first));catalog=next;_memories.clear();diagnostics.addAll(next.warnings);scene.combat.reset();await scene.selectCreature(null,'enemy');await scene.selectCreature(null,'mount');await scene.selectCreature(null,'wing');await scene.setWorld(null);await scene.setSky(null);progress='${lib.files.length} recursos · solo lectura';}
    catch(e){if(catalog!=scene.catalog)scene.catalog=old;progress='No se pudo conectar DATA: $e';showError(e);}finally{if(mounted){setState(()=>importing=false);focus.requestFocus();}}
  }
  @override void dispose(){scene.removeListener(refresh);scene.dispose();renderer.dispose();focus.dispose();xController.dispose();zController.dispose();super.dispose();}
  bool get disabled=>working||importing||!scene.ready;
  Widget field<T>(String key,String title,List<T> items,T? value,String Function(T) id,String Function(T) label,Future<void> Function(T) apply,{String Function(T)? detail,String empty='Sin selección'})=>AssetSelector<T>(key:ValueKey(key),title:title,items:items,value:value,id:id,label:label,detail:detail,memory:_memories.putIfAbsent(key,SelectionMemory.new),enabled:!importing&&scene.ready,emptyLabel:empty,onError:showError,onChanged:(v)async{scene.clearMovement();await apply(v);});
  Widget section(String title,List<Widget> children,{String? help})=>Padding(padding:const EdgeInsets.only(bottom:16),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Row(children:[Expanded(child:Text(title,style:const TextStyle(fontSize:12,fontWeight:FontWeight.w600,color:Color(0xffdbe3f1)))),if(help!=null)Tooltip(message:help,child:const Padding(padding:EdgeInsets.only(left:6),child:Icon(Icons.info_outline,size:14,color:Color(0xff8394af))))]),const SizedBox(height:10),...children]));
  Widget note(String value)=>Padding(padding:const EdgeInsets.symmetric(vertical:6),child:Text(value,style:const TextStyle(fontSize:10,color:Color(0xff98a8bf),height:1.5)));
  Widget slider(String title,double value,double min,double max,ValueChanged<double> change)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(title,style:const TextStyle(fontSize:10,color:Color(0xffaebbd0)))),Text(value.toStringAsFixed(2),style:const TextStyle(fontSize:10))]),SizedBox(height:28,child:Slider(value:value.clamp(min,max),min:min,max:max,onChanged:disabled?null:change))]);
  Widget toggle(String text,bool value,ValueChanged<bool>? change)=>SwitchListTile.adaptive(contentPadding:EdgeInsets.zero,dense:true,visualDensity:VisualDensity.compact,title:Text(text,style:const TextStyle(fontSize:11)),value:value,onChanged:change);
  String creatureId(CreatureRecord c)=>'${c.source}#${c.id}';String partId(PartRecord p)=>'${p.tablePath}#${p.raw.id}';
  Widget partField(Slot slot){final a=scene.appearance!.archetype,p=scene.appearance!.selected[slot];return Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:field<PartRecord>('${a.race}/${a.id}/${slot.name}',slotLabels[slot]!,a.parts[slot]??[],p,partId,(p)=>p.label,(v)=>scene.setAppearance(scene.appearance!.withPart(slot,v)),detail:(p)=>'${p.raw.mesh} · ${p.raw.texture}',empty:slot==Slot.helmet?'Sin casco':'Base / integrado en el traje')),if(![Slot.face].contains(slot))SizedBox(width:25,child:IconButton(padding:EdgeInsets.zero,tooltip:slot==Slot.hair?'Quitar cabello':'Retirar pieza / restaurar base',onPressed:disabled?null:()=>act(()=>scene.setAppearance(scene.appearance!.withPart(slot,null))),icon:const Icon(Icons.remove_circle_outline,size:16)))]);}
  Widget creatureField(String kind){final c=catalog!,items=kind=='mount'?c.mounts:kind=='wing'?c.wings:c.creatures,current=kind=='mount'?scene.mountRecord:kind=='wing'?scene.wingRecord:scene.enemyRecord;return field<CreatureRecord>(kind,kind=='mount'?'Montura':kind=='wing'?'Alas':'Oponente',items,current,creatureId,c.creatureLabel,(v)=>scene.selectCreature(v,kind),detail:(v)=>v.parts.map((p)=>p.mesh).join(' · '),empty:kind=='mount'?'A pie':'Ninguno');}
  Widget panel(){
    final c=catalog,a=scene.appearance?.archetype;if(c==null||a==null)return section('Biblioteca local',[note('Conecta la carpeta DATA descomprimida. Los recursos permanecen en tu equipo.'),FilledButton.icon(onPressed:disabled?null:()=>connect(),icon:const Icon(Icons.folder_open,size:17),label:const Text('Seleccionar DATA')),note(progress)]);
    switch(tab){
      case 0:return Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[section('Identidad',[
        field<String>('race','Raza',c.archetypes.map((x)=>x.race).toSet().toList(),a.race,(x)=>x,(x)=>raceLabels[x]??x,(v)=>scene.setAppearance(Appearance.initial(c.archetypes.firstWhere((x)=>x.race==v)))),field<Archetype>('${a.race}/archetype','Cuerpo / arquetipo',c.archetypes.where((x)=>x.race==a.race).toList(),a,(x)=>'${x.race}/${x.id}',(x)=>x.label,(v)=>scene.setAppearance(Appearance.initial(v))),partField(Slot.face),partField(Slot.hair)]),section('Apariencia guardada',[Row(children:[Expanded(child:OutlinedButton(onPressed:disabled?null:()=>act(saveAppearance),child:const Text('Guardar',style:TextStyle(fontSize:11)))),const SizedBox(width:6),Expanded(child:OutlinedButton(onPressed:disabled?null:()=>act(loadAppearance),child:const Text('Recuperar',style:TextStyle(fontSize:11))))])]),section('Cuerpo base',[OutlinedButton.icon(onPressed:disabled?null:()=>act(()async{final look=scene.appearance!;await scene.setAppearance(Appearance(look.archetype,{for(final s in Slot.values)s:[Slot.face,Slot.hair].contains(s)?look.selected[s]:null}));}),icon:const Icon(Icons.accessibility_new,size:16),label:const Text('Restaurar base',style:TextStyle(fontSize:11))),note('La base utiliza los recursos originales disponibles; no se inventa un cuerpo desnudo.')])]);
      case 1:return Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[section('Conjunto',[field<String>('${a.race}/${a.id}/set','Atuendo completo',a.sets.keys.toList(),scene.appearance!.selected[Slot.upper]?.key,(s)=>s,displaySet,(v)=>scene.setAppearance(Appearance.forSet(scene.appearance!.archetype,v,previous:scene.appearance)),detail:(s)=>a.sets[s]!.values.map((p)=>p.raw.texture).join(' · '))],help:'Un conjunto sustituye todas las piezas incompatibles. ↑ y ↓ recorren el catálogo cuando este campo tiene el foco.'),section('Piezas',[for(final s in [Slot.upper,Slot.lower,Slot.hand,Slot.foot,Slot.helmet])partField(s)]),section('Armas',[field<WeaponRecord>('weapons','Equipo de combate',c.weapons,scene.weaponRecord,(w)=>'${w.source}#${w.id}',weaponLabel,scene.equip,detail:(w)=>'${w.mesh} · ${w.texture}',empty:'Sin arma'),TextButton(onPressed:disabled?null:()=>act(()=>scene.equip(null)),child:const Text('Quitar arma',style:TextStyle(fontSize:11)))],help:'Se conservan los anclajes originales IT2. Las armas dobles utilizan ambas manos cuando el perfil lo define.')]);
      case 2:return Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[section('Alas',[creatureField('wing'),if(scene.wing!=null)...[actorAnimation(scene.wing!,'wing'),slider('Altura del anclaje',scene.wingHeight,-2,4,(v)=>setState(()=>scene.wingHeight=v)),slider('Separación de espalda',scene.wingDepth,-2,2,(v)=>setState(()=>scene.wingDepth=v)),slider('Escala',scene.wingSize,.1,3,(v)=>setState(()=>scene.wingSize=v)),TextButton(onPressed:disabled?null:()=>act(()=>scene.selectCreature(null,'wing')),child:const Text('Quitar alas',style:TextStyle(fontSize:11)))],note('El anclaje sigue el torso y la transformación del jinete, también al montar.')]),section('Montura',[creatureField('mount'),if(scene.mount!=null)...[actorAnimation(scene.mount!,'mount'),slider('Altura del asiento',scene.riderHeight,0,6,(v)=>setState(()=>scene.riderHeight=v)),slider('Avance del asiento',scene.riderForward,-3,3,(v)=>setState(()=>scene.riderForward=v)),TextButton(onPressed:disabled?null:()=>act(()=>scene.selectCreature(null,'mount')),child:const Text('Desmontar',style:TextStyle(fontSize:11))),note('W: marcha · W + Shift: carrera. El ajuste de asiento se recuerda por montura durante la sesión.')]])]);
      case 3:return Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[section('Prueba de combate',[creatureField('enemy'),if(scene.enemy!=null)...[actorAnimation(scene.enemy!,'enemy'),slider('Distancia al personaje',scene.enemyDistance.clamp(.5,12),.5,12,(v)=>setState((){scene.enemy!.root.position.x=(scene.character?.root.position.x??0)+v;scene.enemy!.root.position.z=scene.character?.root.position.z??0;}))],toggle('Contraataque',scene.combat.counterattack,(v)=>setState(()=>scene.combat.counterattack=v)),toggle('Ataque automático',scene.combat.automatic,scene.enemy==null||scene.mount!=null?null:(v){if(v){act(()async{await scene.attack();scene.combat.automatic=true;});}else{setState(()=>scene.combat.automatic=false);}}),slider('Daño del personaje',scene.combat.damage,10,250,(v)=>setState(()=>scene.combat.damage=v)),slider('Daño de criatura',scene.combat.enemyDamage,10,150,(v)=>setState(()=>scene.combat.enemyDamage=v)),slider('Alcance',scene.combat.range,1,12,(v)=>setState(()=>scene.combat.range=v)),OutlinedButton(onPressed:scene.resetCombat,child:const Text('Reiniciar prueba',style:TextStyle(fontSize:11)))],help:'Simulación local. No reproduce las fórmulas del servidor.'),section('Efectos y sonido',[toggle('Activar audio',scene.sound,(v)=>setState(()=>scene.sound=v)),field<String>('impact','Textura de impacto',c.effects,scene.effectPath,(s)=>s,baseName,scene.setEffect,detail:(s)=>s,empty:'Sin textura'),field<String>('audio','Sonido / música',c.sounds,lastSound.isEmpty?null:lastSound,(s)=>s,baseName,(v)async{scene.sound=true;await scene.playSound(v);setState(()=>lastSound=v);},detail:(s)=>s),note('Texturas y audio originales. El impacto del laboratorio no sustituye todas las secuencias EFT.')]),section('Registro',[SelectableText(scene.combat.log.take(12).join('\n'),style:const TextStyle(fontSize:10,height:1.6))])]);
      case 4:return Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[section('Escenario',[field<String>('world','Mapa exterior',c.worlds,scene.worldPath,(s)=>s,(s)=>'Mapa ${baseName(s).replaceFirst('.wld','')}',(v)=>scene.setWorld(v),detail:(s)=>s,empty:'Estudio'),field<String>('sky','Cielo',c.skies,scene.skyPath,(s)=>s,baseName,scene.setSky,detail:(s)=>s,empty:'Sin cielo'),Row(children:[Expanded(child:TextButton(onPressed:disabled?null:()=>act(()=>scene.setWorld(null)),child:const Text('Estudio',style:TextStyle(fontSize:11)))),Expanded(child:TextButton(onPressed:disabled?null:()=>act(()=>scene.setSky(null)),child:const Text('Sin cielo',style:TextStyle(fontSize:11))))]),Row(children:[Expanded(child:TextField(controller:xController,style:const TextStyle(fontSize:11),keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'X'))),const SizedBox(width:7),Expanded(child:TextField(controller:zController,style:const TextStyle(fontSize:11),keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Z')))]),const SizedBox(height:8),OutlinedButton(onPressed:disabled||scene.worldPath==null?null:()=>act(()async{final x=double.tryParse(xController.text),z=double.tryParse(zController.text);if(x==null||z==null)throw const FormatException('Escribe dos coordenadas numéricas.');await scene.setWorld(scene.worldPath,x:x,z:z);}),child:const Text('Cargar sector',style:TextStyle(fontSize:11))),note('Sector ${scene.originX.round()}, ${scene.originZ.round()} · 128 × 128 m. Sin colisión con edificios; los WLD de mazmorras DG no se interpretan todavía.')]),section('Visualización',[toggle('Malla de alambre',scene.wireframe,scene.setWireframe),slider('Cámara',scene.distance,.4,60,(v){scene.distance=v;scene.updateCamera();}),slider('Altura del encuadre',scene.targetY,-1,6,(v){scene.targetY=v;scene.updateCamera();}),OutlinedButton.icon(onPressed:()=>act(capture),icon:const Icon(Icons.photo_camera_outlined,size:16),label:const Text('Captura PNG',style:TextStyle(fontSize:11)))])]);
      default:return Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[section('Recursos indexados',[Text('${c.library.files.length} recursos\n${c.archetypes.length} arquetipos\n${c.weapons.length} armas\n${c.creatures.length} criaturas\n${c.mounts.length} registros de monturas\n${c.wings.length} alas\n${c.worlds.length} mapas\n${c.skies.length} cielos',style:const TextStyle(fontSize:11,height:1.75)),const SizedBox(height:10),OutlinedButton(onPressed:()=>act(exportDiagnostics),child:const Text('Exportar diagnóstico',style:TextStyle(fontSize:11))),note('Las listas contienen recursos encontrados, no combinaciones exhaustivamente homologadas.')]),SelectableText(diagnostics.take(45).join('\n\n'),style:const TextStyle(fontSize:10,height:1.45))]);
    }
  }
  Widget actorAnimation(Actor a,String target){final names=a.clips.keys.toList();final selected=names.where((s)=>a.clips[s]==a.clip).firstOrNull;return field<String>('$target/animation','Animación',names,selected,(s)=>s,(s)=>s,(v)=>scene.previewActorAnimation(target,v));}
  Actor? get inspected=>switch(inspectorTarget){'Montura'=>scene.mount,'Alas'=>scene.wing,'Criatura'=>scene.enemy,_=>scene.character};
  Widget inspector(){final actor=inspected;return Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[section('Objeto inspeccionado',[DropdownButton<String>(value:inspectorTarget,isExpanded:true,items:['Personaje','Montura','Alas','Criatura'].map((s)=>DropdownMenuItem(value:s,child:Text(s,style:const TextStyle(fontSize:12)))).toList(),onChanged:(s)=>setState(()=>inspectorTarget=s!)),if(actor==null)note('No hay un objeto de este tipo cargado.')else ...[Text('${actor.parts.fold(0,(n,p)=>n+p.data.triangles)} triángulos · ${actor.world.length} huesos',style:const TextStyle(fontSize:10,color:Color(0xffa7b8d1))),note(actor.clip==null?'Sin animación':'${animationLabel(actor.clip!.source)}\n${baseName(actor.clip!.source)}'),slider('Velocidad de reproducción',actor.speed,.1,2,(v)=>setState(()=>actor.speed=v)),toggle('Reproducción',actor.playing,(v)=>setState(()=>actor.playing=v)),if(actor.clip!=null)note('Duración ${actor.clip!.duration.toStringAsFixed(2)} s\nTiempo ${actor.time.toStringAsFixed(2)} s\nPosición X ${actor.root.position.x.toStringAsFixed(2)} / Y ${actor.root.position.y.toStringAsFixed(2)} / Z ${actor.root.position.z.toStringAsFixed(2)}')]]),section('Atajos',[note('W A S D  —  caminar\nShift + dirección  —  correr\n1–4  —  ataques disponibles\nR  —  reiniciar combate\nArrastrar  —  orbitar\nRueda / pellizco  —  acercar\n↑ / ↓ en un selector  —  cambiar recurso\nIntro en el selector  —  catálogo'),note('Los atajos del personaje solo actúan cuando el visor tiene el foco. No interfieren con las búsquedas.')]),if(scene.combat.log.isNotEmpty)section('Últimos eventos',[Text(scene.combat.log.take(5).join('\n'),style:const TextStyle(fontSize:10,height:1.5))])]);}
  Widget timeline(){
    final a=scene.character;if(a==null)return const SizedBox.shrink();
    return LayoutBuilder(builder:(context,constraints){final clip=a.clip;final progress=clip==null?0.0:((a.loop?a.time%clip.duration:a.time.clamp(0.0,clip.duration))/clip.duration).clamp(0.0,1.0);
      return Column(mainAxisSize:MainAxisSize.min,children:[Row(children:[IconButton(tooltip:a.playing?'Pausar':'Reproducir',onPressed:()=>setState(()=>a.playing=!a.playing),icon:Icon(a.playing?Icons.pause:Icons.play_arrow,size:20)),Expanded(child:InkWell(onTap:()=>act(()async{final memory=_memories.putIfAbsent('character/animation',SelectionMemory.new);final p=await showDialog<String>(context:context,builder:(_)=>AssetPickerDialog<String>(title:'Animaciones del personaje',items:scene.animations,current:clip?.source,id:(x)=>x,label:animationLabel,detail:baseName,memory:memory));if(p!=null)await scene.selectAnimation(p);}),child:Row(children:[Expanded(child:Text(clip==null?'Sin animación':animationLabel(clip.source),style:const TextStyle(fontSize:11),maxLines:1,overflow:TextOverflow.ellipsis)),const Icon(Icons.expand_more,size:16)]))),if(constraints.maxWidth>350)...[const SizedBox(width:14),Text('${(clip==null?0:progress*clip.duration).toStringAsFixed(2)} / ${clip?.duration.toStringAsFixed(2)??'0'} s',style:const TextStyle(fontSize:10,color:Color(0xff8fa1bb)))],PopupMenuButton<double>(tooltip:'Velocidad',onSelected:(v)=>setState(()=>a.speed=v),itemBuilder:(_)=>[.25,.5,1.0,1.5,2.0].map((v)=>PopupMenuItem(value:v,child:Text('$v×'))).toList(),child:Padding(padding:const EdgeInsets.all(10),child:Text('${a.speed.toStringAsFixed(2)}×',style:const TextStyle(fontSize:10))))]),SizedBox(height:18,child:Slider(value:progress,onChanged:clip==null?null:(v){scene.clearMovement();a.time=v*clip.duration;a.playing=false;a.pose();setState((){});})),const SizedBox(height:4)]);
    });
  }
  Future<void> performAttack([int index=0]) async {if(disabled||scene.enemy==null)return;try{scene.clearMovement();scene.attackCounter=index;await scene.attack();focus.requestFocus();}catch(e){showError(e);}}
  Widget actionBar()=>SizedBox(height:48,child:ListView(scrollDirection:Axis.horizontal,padding:const EdgeInsets.symmetric(horizontal:10,vertical:5),children:[for(var i=0;i<scene.attackClips.length&&i<4;i++)Padding(padding:const EdgeInsets.only(right:6),child:Tooltip(message:'${i+1}: ${baseName(scene.attackClips[i].source)}',child:SizedBox(width:91,child:FilledButton.tonal(onPressed:disabled||scene.enemy==null||scene.mount!=null||scene.combat.cooldownRemaining>0?null:()=>performAttack(i),style:FilledButton.styleFrom(padding:const EdgeInsets.symmetric(horizontal:9),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(6))),child:Row(children:[Text('${i+1}',style:const TextStyle(fontSize:10,fontWeight:FontWeight.w700)),const SizedBox(width:8),Expanded(child:Text(scene.combat.cooldownRemaining>0?'${scene.combat.cooldownRemaining.toStringAsFixed(1)} s':'Ataque ${i+1}',style:const TextStyle(fontSize:10)))]))))),OutlinedButton.icon(onPressed:scene.enemy==null?null:(){scene.resetCombat();focus.requestFocus();},icon:const Icon(Icons.restart_alt,size:16),label:const Text('Reiniciar',style:TextStyle(fontSize:10))),const SizedBox(width:9),Center(child:Text(scene.mount!=null?'Montado · W / Shift':scene.enemy==null?'Selecciona un oponente en Combate':'Alcance ${scene.enemyDistance.toStringAsFixed(1)} / ${scene.combat.range.toStringAsFixed(1)} m',style:const TextStyle(fontSize:10,color:Color(0xff99a9c2))))]));
  Widget healthBar(String label,double hp)=>SizedBox(width:158,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(label,style:const TextStyle(fontSize:10,color:Color(0xffdfe7f6)))),Text('${hp.round()}',style:const TextStyle(fontSize:10,color:Color(0xffdfe7f6)))]),const SizedBox(height:5),LinearProgressIndicator(value:(hp/scene.combat.maxHealth).clamp(0.0,1.0),minHeight:4,borderRadius:BorderRadius.circular(3))]));
  Widget viewport()=>RepaintBoundary(key:captureKey,child:Stack(children:[Positioned.fill(child:renderer.build()),Positioned.fill(child:ViewportMovementInput(focusNode:focus,onChanged:(x,z,run)=>scene.setMovement(x,z,run:run),onAction:(key){final keys=[LogicalKeyboardKey.digit1,LogicalKeyboardKey.digit2,LogicalKeyboardKey.digit3,LogicalKeyboardKey.digit4];final index=keys.indexOf(key);if(index>=0&&index<scene.attackClips.length)performAttack(index);if(key==LogicalKeyboardKey.keyR)scene.resetCombat();},child:Listener(onPointerSignal:(event){if(event is PointerScrollEvent)scene.zoom(event.scrollDelta.dy>0?1.08:1/1.08);},child:GestureDetector(behavior:HitTestBehavior.opaque,onTap:focus.requestFocus,onScaleStart:(_){gestureScale=1;focus.requestFocus();},onScaleUpdate:(d){if(d.pointerCount==1){scene.orbit(d.focalPointDelta.dx,d.focalPointDelta.dy);}else{scene.zoom(gestureScale/d.scale);gestureScale=d.scale;}},child:const SizedBox.expand())))),
    Positioned(top:12,left:14,right:14,child:IgnorePointer(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(scene.appearance?.archetype.label??'Estudio 3D',style:const TextStyle(fontSize:13,fontWeight:FontWeight.w500,color:Color(0xffe8edf8),shadows:[Shadow(blurRadius:6,color:Colors.black)])),const SizedBox(height:4),Text(scene.mount!=null?'Montado · ${scene.running?'Carrera':'Marcha'}':scene.walkX!=0||scene.walkZ!=0?(scene.running?'Corriendo':'Caminando'):'Vista libre',style:const TextStyle(fontSize:10,color:Color(0xffb9c9df),shadows:[Shadow(blurRadius:4,color:Colors.black)])),if(scene.enemy!=null)Padding(padding:const EdgeInsets.only(top:12),child:Container(padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:const Color(0xd9182130),borderRadius:BorderRadius.circular(7)),child:Wrap(spacing:18,runSpacing:10,children:[healthBar('Personaje',scene.combat.playerHealth),healthBar('Oponente',scene.combat.enemyHealth)]))),if(scene.hitLife>0)Padding(padding:const EdgeInsets.only(top:8),child:Text(scene.lastImpact,style:const TextStyle(fontSize:16,fontWeight:FontWeight.bold,color:Color(0xffffd6a1),shadows:[Shadow(blurRadius:5,color:Colors.black)])))]))),
    if(catalog==null&&!importing)Center(child:SingleChildScrollView(child:Container(constraints:const BoxConstraints(maxWidth:350),padding:const EdgeInsets.all(25),margin:const EdgeInsets.all(24),decoration:BoxDecoration(color:const Color(0xf51b2638),borderRadius:BorderRadius.circular(12),border:Border.all(color:const Color(0xff35465f))),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[const Icon(Icons.view_in_ar_outlined,size:28,color:Color(0xffadc1ff)),const SizedBox(height:18),const Text('Tu biblioteca.\nTu espacio 3D.',style:TextStyle(fontSize:27,height:1.2)),const SizedBox(height:12),const Text('Personajes, equipo y escenarios originales. Selecciona DATA para comenzar.',style:TextStyle(fontSize:12,color:Color(0xffa7b7ce),height:1.6)),const SizedBox(height:18),FilledButton.icon(onPressed:disabled?null:()=>connect(),icon:const Icon(Icons.folder_open,size:17),label:const Text('Conectar DATA'))])))),
    if(scene.character!=null)Positioned(bottom:12,right:12,child:Column(children:[GestureDetector(onTap:()=>setState(()=>scene.touchRun=!scene.touchRun),child:Tooltip(message:'Correr con los controles táctiles',child:Container(width:40,height:28,decoration:BoxDecoration(color:scene.touchRun?const Color(0xff536d9f):const Color(0xc8232d40),borderRadius:BorderRadius.circular(5)),child:const Icon(Icons.directions_run,size:17)))),const SizedBox(height:3),movePad(Icons.arrow_upward,0,-1),Row(children:[movePad(Icons.arrow_back,-1,0),movePad(Icons.arrow_downward,0,1),movePad(Icons.arrow_forward,1,0)])])),
    if(importing||working||scene.busy)Positioned(bottom:12,left:12,child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:225),child:Container(padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:const Color(0xec1c293d),borderRadius:BorderRadius.circular(6)),child:Row(mainAxisSize:MainAxisSize.min,children:[const SizedBox(width:13,height:13,child:CircularProgressIndicator(strokeWidth:1.5)),const SizedBox(width:9),Flexible(child:Text(importing?progress:'Preparando recursos…',maxLines:2,style:const TextStyle(fontSize:10)))]))))]));
  Widget movePad(IconData icon,double x,double z)=>Listener(onPointerDown:(_){scene.setMovement(x,z,run:scene.touchRun);},onPointerUp:(_){scene.clearMovement();},onPointerCancel:(_){scene.clearMovement();},child:Container(margin:const EdgeInsets.all(2),width:32,height:29,decoration:BoxDecoration(color:const Color(0xc8232d40),borderRadius:BorderRadius.circular(5)),child:Icon(icon,size:16,color:const Color(0xffc6d3e8))));
  Future<File> saveFile(String name,String content) async {final dir=await getApplicationDocumentsDirectory();final folder=Directory('${dir.path}/HerramientaShaiya');await folder.create(recursive:true);final f=File('${folder.path}/$name');await f.writeAsString(content,flush:true);scene.say('Guardado: ${f.path}');return f;}
  Future<void> saveAppearance() async {final look=scene.appearance!;await saveFile('apariencia.json',jsonEncode({'version':1,'archetype':look.archetype.id,'race':look.archetype.race,'fullCostume':look.fullCostume,'slots':{for(final e in look.selected.entries)e.key.name:e.value?.raw.id}}));}
  Future<void> loadAppearance() async {final dir=await getApplicationDocumentsDirectory(),f=File('${dir.path}/HerramientaShaiya/apariencia.json');if(!await f.exists())throw const FormatException('No hay una apariencia guardada.');final data=jsonDecode(await f.readAsString()) as Map;final a=catalog!.archetypes.where((a)=>a.id==data['archetype']&&a.race==data['race']).firstOrNull;if(a==null)throw const FormatException('El arquetipo guardado no existe en DATA.');final slots=<Slot,PartRecord?>{};for(final s in Slot.values){final id=(data['slots'] as Map)[s.name];slots[s]=id==null?null:a.parts[s]!.where((p)=>p.raw.id==id).firstOrNull;if(id!=null&&slots[s]==null)throw FormatException('No se encuentra ${s.name} #$id.');}await scene.setAppearance(Appearance(a,slots,fullCostume:data['fullCostume']==true));}
  Future<void> exportDiagnostics() async {await saveFile('diagnostico.json',const JsonEncoder.withIndent('  ').convert({'version':'0.2.0','time':DateTime.now().toIso8601String(),'platform':Platform.operatingSystem,'resources':catalog?.library.files.length,'messages':diagnostics}));}
  Future<void> capture() async {final boundary=captureKey.currentContext?.findRenderObject() as RenderRepaintBoundary?;if(boundary==null)return;final im=await boundary.toImage(pixelRatio:1.5);final bytes=await im.toByteData(format:ui.ImageByteFormat.png);im.dispose();if(bytes==null)throw const FormatException('No se pudo capturar el visor.');final dir=await getApplicationDocumentsDirectory(),f=File('${dir.path}/Shaiya_${DateTime.now().millisecondsSinceEpoch}.png');await f.writeAsBytes(bytes.buffer.asUint8List());scene.say('Captura guardada: ${f.path}');}
  @override Widget build(BuildContext context)=>StudioWorkspace(viewport:viewport(),left:panel(),right:inspector(),timeline:timeline(),actions:actionBar(),hasLibrary:scene.character!=null,onOpenData:disabled?null:()=>connect(),tabs:const ['Personaje','Equipamiento','Alas y monturas','Combate','Escenario','Diagnóstico'],icons:const [Icons.person_outline,Icons.shield_outlined,Icons.pets_outlined,Icons.sports_martial_arts,Icons.landscape_outlined,Icons.fact_check_outlined],selectedTab:tab,onTab:(v){scene.clearMovement();setState(()=>tab=v);},status:Row(children:[const Icon(Icons.lock_outline,size:11,color:Color(0xff8cbaa3)),const SizedBox(width:7),Expanded(child:Text(scene.status,maxLines:1,overflow:TextOverflow.ellipsis)),const SizedBox(width:10),const Text('Local · Solo lectura')]));
}
