// Complete local regression runner. Keep synchronized with test/*_test.dart.
import '../test/archive_export_test.dart' as suite0;
import '../test/archive_test.dart' as suite1;
import '../test/body_coverage_test.dart' as suite2;
import '../test/client_locale_test.dart' as suite3;
import '../test/core_test.dart' as suite4;
import '../test/editor_advanced_test.dart' as suite5;
import '../test/editor_document_test.dart' as suite6;
import '../test/editor_import_regression_test.dart' as suite7;
import '../test/editor_storage_test.dart' as suite8;
import '../test/editor_ui_test.dart' as suite9;
import '../test/editor_workbench_test.dart' as suite10;
import '../test/equipment_slot_mapping_test.dart' as suite11;
import '../test/excelxml_document_test.dart' as suite12;
import '../test/excelxml_semantics_test.dart' as suite43;
import '../test/extra_motion_test.dart' as suite13;
import '../test/flight_key_input_test.dart' as suite14;
import '../test/flight_responsiveness_test.dart' as suite45;
import '../test/flight_v3_bundle_test.dart' as suite15;
import '../test/gameplay_regression_test.dart' as suite16;
import '../test/local_game_test.dart' as suite17;
import '../test/locomotion_test.dart' as suite18;
import '../test/manual_flight_regression_test.dart' as suite19;
import '../test/mon_editor_test.dart' as suite20;
import '../test/mounted_supplement_test.dart' as suite21;
import '../test/movement_input_test.dart' as suite22;
import '../test/offline_saves_test.dart' as suite23;
import '../test/palette_test.dart' as suite24;
import '../test/recovery_test.dart' as suite25;
import '../test/revision04_test.dart' as suite26;
import '../test/rig_transition_test.dart' as suite27;
import '../test/spk_archive_test.dart' as suite28;
import '../test/spk_extended_formats_test.dart' as suite29;
import '../test/spk_fragment_payload_test.dart' as suite30;
import '../test/spk_payload_validation_test.dart' as suite31;
import '../test/spk_profile_discovery_test.dart' as suite32;
import '../test/spk_table_discovery_test.dart' as suite33;
import '../test/spk_writer_test.dart' as suite34;
import '../test/streaming_test.dart' as suite35;
import '../test/vehicle_position_test.dart' as suite36;
import '../test/wing_item_mapping_test.dart' as suite37;
import '../test/wing_motion_test.dart' as suite38;
import '../test/wing_native_transform_test.dart' as suite46;
import '../test/wing_position_test.dart' as suite39;
import '../test/wing_systems_test.dart' as suite40;
import '../test/workspace_interaction_test.dart' as suite41;
import '../test/workspace_material_test.dart' as suite42;
import '../test/xml_tree_document_test.dart' as suite44;

void main() {
  suite0.main();
  suite1.main();
  suite2.main();
  suite3.main();
  suite4.main();
  suite5.main();
  suite6.main();
  suite7.main();
  suite8.main();
  suite9.main();
  suite10.main();
  suite11.main();
  suite12.main();
  suite13.main();
  suite14.main();
  suite15.main();
  suite16.main();
  suite17.main();
  suite18.main();
  suite19.main();
  suite20.main();
  suite21.main();
  suite22.main();
  suite23.main();
  suite24.main();
  suite25.main();
  suite26.main();
  suite27.main();
  suite28.main();
  suite29.main();
  suite30.main();
  suite31.main();
  suite32.main();
  suite33.main();
  suite34.main();
  suite35.main();
  suite36.main();
  suite37.main();
  suite38.main();
  suite39.main();
  suite40.main();
  suite41.main();
  suite42.main();
  suite43.main();
  suite44.main();
  suite45.main();
  suite46.main();
}
